headsetapp/headset-electron

- index.js
- package.json
- yarn.lock
Added changes from issue, not sure if I need to add these changes to all the master branches or not.
> Saving window position

- .travis.yml
- README.md
Adding deployment to packagecloud.io from Travis
> add deploy script

- linux/index.js
- windows/index.js
Reference : #63 
I remove useless commit and modified yarn.lock
> Execute only one instnace (Linux/Windows)

- .travis.yml
- README.md
- appveyor.yml
- darwin/package-lock.json
- darwin/package.json
- linux/package-lock.json
- linux/package.json
- package-lock.json
- package.json
- windows/bin/winstaller.js
- windows/package-lock.json
- windows/package.json
Some packages have also been updated to their latest versions
> Add AppVeyor support

- .travis.yml
- darwin/package-lock.json
- darwin/package.json
- linux/package-lock.json
- linux/package.json
- package-lock.json
- package.json
- windows/package-lock.json
- windows/package.json
This PR updates various packages to their latest versions (including bug fixes for `electron` and `eslint`). It also fixes issue #81 and makes `travis.yml` more readable
> Fixes before_deploy script errors

- auto_updater.json
- bin/bump_auto_updater.sh
- package.json
Break #107 into two parts
1. Part one: add the script to update `auto_updater.json`
2. Part two: test the release cycle process. (Next PR)
> add bump_auto_updater script

- README.md
- linux/index.js
- windows/index.js
This will help people that are trying to build on 32bit systems, and "fixes" issue #9
> Readme and isDev fixes

- darwin/package-lock.json
- darwin/package.json
- linux/package-lock.json
- linux/package.json
- shared/player/ytPlayer.js
- windows/package-lock.json
- windows/package.json
Changes:
- Remove controls
- Remove video title
- Remove keyboard bindings (only from the player. the main window still works)
- update foreman for development 
Benefits:
1. Reduce the confusion of two things that need to be controlled
2. Looks better and cleaner
3. Gives more power to the main window
Disadvantages:
1. Can't change speed and quality (maybe the app will support that one day)
Before:
After:
> update player parameters and update foreman

- CONTRIBUTING.md
- README.md
I didn't know how to get started contributing, so I created a contributor doc. 
Up for feedback, specifically:
- all are the steps for installation included?
- is this the right git flow?
- what are the ways to contribute to Headset?
> Add a doc for contributors.

- appveyor.yml
- windows/index.js
- windows/package-lock.json
- windows/package.json
> Windows autoupdater

- .chocolatey/headset.nuspec
- .chocolatey/tools/chocolateyInstall.ps1
- bin/choco_version_bump.sh
Fixes more problems with chocolatey
> More choco

- shared/player/style.css
> Allow player to scale with the size of the window

- darwin/bin/build_pack.sh
- linux/bin/build_package.sh
- package-lock.json
- windows/package.json
It seems that the regex pattern was still not strong enough and some errors were creeping out due to missing files/modules
> Better regex pattern when excluding files/directories while packaging

- .chocolatey/headset.nuspec
- .chocolatey/tools/chocolateyInstall.ps1
- auto_updater.json
- darwin/package-lock.json
- darwin/package.json
- linux/package-lock.json
- linux/package.json
- package-lock.json
- package.json
- windows/package-lock.json
- windows/package.json
Electron v2.0.2 is suffering from this bug https://github.com/electron/electron/issues/13043
> Downgrade electron for windows to 1.8.7

- windows/index.js
- windows/lib/headset-logger.js
- windows/lib/headsetTray.js
The new module will produce a file of ~24Mb size for a whole year, based on listening for 5 hours a day, 5 days a week.
> Move windows logger to its own module

- darwin/bin/player-window.sh
- linux/bin/player-window.sh
- shared/player/ytPlayer.js
- windows/Procfile
This PR will fix issue #153 and it might make it possible to fix #10 
The required logic on the core has also been updated
> Unavailable videos fix

- linux/lib/mprisService.js
Playing status is controlled by the player window and not main
> Fix for mpris and mediaKeys

- windows/index.js
> Fixes typo on Windows for logger

- darwin/index.js
- windows/index.js
> Fix new docs-window being unclosable on macOS and Windows

- darwin/lib/i18nextConfig.js
- windows/lib/i18nextConfig.js
> Fix i18next-node-remote-backend not loading

- .travis.yml
- CONTRIBUTING.md
- README.md
- appveyor.yml
- darwin/bin/build_installer.sh
- darwin/index.js
- darwin/lib/registerMediaKeys.js
- darwin/package-lock.json
- darwin/package.json
- linux/bin/configurations/config_deb.json
- linux/index.js
- linux/package-lock.json
- linux/package.json
- package-lock.json
- package.json
- windows/index.js
- windows/lib/registerMediaKeys.js
- windows/package-lock.json
- windows/package.json
This PR is doing the following:
- Upgrade to electron 5
- Fix any breaking API changes when upgrading to electron 5
- Clean up and re-arrange code for all OSs
- Ask the user to allow Headset to control media keys on macOS
- Create DMG installer with a Headset icon
> Upgrade to electron 5 and other improvements

- package-lock.json
- package.json
- src/index.js
- src/lib/discord.js
- src/lib/headsetLogger.js
This needs also needs support implemented in the core.
This fixes #232
> Add Discord support

- src/index.js
- src/lib/headsetTray.js
- src/lib/mediaKeys/linux.js
- src/lib/mediaKeys/macOSWindows.js
- src/lib/mprisService.js
This will require merging the same PR on the core side
> replace electronConnector with webContents.send

- package-lock.json
- package.json
- src/lib/discord.js
The button directs people to check the official Headset site
> feat: add button to Discord RPC

- .chocolatey/headset.nuspec
- .chocolatey/tools/chocolateyInstall.ps1
- co.headsetapp.headset.metainfo.xml
- package-lock.json
- package.json
> Upgrade to 3.3.1

- package-lock.json
- package.json
- src/index.js
The new version introduces some requirements regarding webPreferences
The commandLine option for autoplay-policy is not needed anymore
> feat: upgrade to electron 12

- src/index.js
Other types of errors can also trigger the dialog
> fix: show error dialog if there's an internet connection problem

- bin/installer/darwin.sh
- bin/packager/darwin.sh
- bin/packager/packager.js
- package-lock.json
- package.json
> feat: add support for macOS arm64 architecture

- .github/workflows/ci.yml
- bin/getTags.sh
- bin/installer/windows.js
- bin/packager/darwin.sh
- bin/packager/entitlements.plist
- bin/packager/packager.js
- src/lib/autoUpdater.js
This fixes signing and notarizing on macOS.
Better check for signing by setting an environment variable `SIGN` to either `yes` or `no`. This allows for easier signing on local computers.
> macOS updates

- .github/workflows/ci.yml
- bin/check_macOS_signatures.sh
- bin/packager/darwin.sh
- bin/packager/packager.js
- package.json
> build: add script for signature and notarization check for macOS
