headsetapp/headset-electron

- bin/build
- config.json
This configuration file works by adding the option `--config config.jason` to `electron-installer-debian`. The command will look like this based on the current setup: `electron-installer-debian --src build/Headset-linux-x64/ --arch amd64 --config config.json`
This configuration file will fix issue #30 and possibly #35. This will also partially fix issue #46 .
Also, issue #11 was not really fixed, there was only a workaround provided for this issue. It can now be properly closed by this.
Also, there's some mention of the .desktop file in issue 16 which can probably be closed too
> Added configuration file for electron-installer-debian

- debian/config.json
- debian/index.js
- debian/package.json
- debian/registerBindings.js
- debian/yarn.lock
This is a workaround to fix issue #5 
There seems to be a bug with electron and how it handles shortcuts that are already registered by the OS. Electron won't register any shortcuts that are already being used by another app or the OS, so normal media shortcuts won't work.
Changing the shortcuts to require `CTRL+(media key)` fixes the issue and works without a problem.
This seems to be a problem in other OS too according to some of the issues posted on the electron project but I wasn't able to confirm this myself.
You can see that other electron apps have the same problem here: [nukeop/nuclear#18](https://github.com/nukeop/nuclear/issues/18) and [twolfson/google-music-electron#45](https://github.com/twolfson/google-music-electron/issues/45)
> Change global shortcuts for linux

- .travis.yml
- debian/Procfile
- debian/bin/build
- debian/index.js
- debian/package.json
- debian/yarn.lock
I've clean up the code for Linux, removing some redundancies and even further fixing the icon issues.
I've also added a Travis file, which is currently working only for the Linux build. It's just simply running `yarn build` to create a working Linux application and package.
You can see the output of this Travis configuration on my [build#17](https://travis-ci.org/fcastilloec/headset-electron/builds/261381397) from my fork.
I'll try to introduce OSX support for Travis in a future commit but because I have no experience with OSX, I'm not sure how successful I'll be.
Also, in a different PR, I'll try to see if Travis can publish the deb file into an APT repository based on whatever decision comes from the discussion in issue #43
> Various Linux fixes and initial Travis support

- windows/index.js
When I close before player is initialized, **player** object is `undefined`.
So `player.close()` will be crash the app
> Return when player has not initialized

- README.md
- linux/bin/build.sh
- linux/bin/config_deb.json
- linux/index.js
- linux/mprisService.js
- linux/package.json
- linux/registerMediaKeys.js
I have tested this code on both 64 and 32 bits and it's working. I also tested it on different desktop environments and some work better than others, here's a list:
| Desktop | Status |
| --- | --- |
| Unity (Ubuntu <= 17.04) | Works |
| Cinnamon (LInux Mint) | Works |
| Elementary OS | Works |
| Budgie | Can control (No album cover) |
| KDE | Can control (seek is broken [kde bug?]) |
| Gnome Shell | Can Control (but there's no feedback or album cover) |
| Mate | Mate doesn't have mpris support |
I'm not 100% sure why some desktops only have partial support, I think it might be because they're very strict when following the `MPRIS` standard and the nodejs implementation has a big bug [issue #1](https://github.com/emersion/mpris-service/issues/1) which might affect reading metadata to …
> MPRIS support

- linux/bin/config_deb.json
- linux/package-lock.json
- linux/package.json
- package.json
The way `electron-installer-debian` handles dependencies has changed. The new way will prevent any dependency issues with distros that we haven't tested. Issues like #72 are going to be less likely.
> Update electron-installer-debian to fix any dependency issue

- .eslintrc
- linux/registerMediaKeys.js
I tried fixing this issues with a `try...catch` but this approach doesn't work with segmentation faults. The only way I could think of fixing this was introducing an additional check on the status of the player before sending the command.
If anybody can think of a better way to do this, do let me know.
> Fix segmentation fault on linux

- darwin/bin/build_pack.sh
- darwin/package-lock.json
- darwin/package.json
- darwin/test/app.test.js
- linux/bin/build_installers.sh
- linux/bin/build_package.sh
- linux/package-lock.json
- linux/package.json
- linux/test/app.test.js
- package-lock.json
- package.json
- windows/bin/winstaller.js
- windows/package-lock.json
- windows/package.json
- windows/test/app.test.js
A new version of `electron-packager` was released which helps keep all OSs builds with the same capitalization in the name.
The appname was **Headset** for all except Linux. Now all OSs appname are **Headset**, and their executables are **headset** to adhere common convention.
> Standardize app-name and executable-name across all OSs

- darwin/index.js
- darwin/package-lock.json
- darwin/package.json
- linux/index.js
- linux/lib/mprisService.js
- linux/package-lock.json
- linux/package.json
- package-lock.json
- package.json
- windows/index.js
- windows/package-lock.json
- windows/package.json
There was a bug with debian installer and productDescription that was fixed with the latest version of `electron-installer-debian`.
Also, errors were shown that `titleBarStyle: 'hidden-inset'` has been deprecated and we need to use `hiddenInset` instead.
It also standardizes the debug outputs across all OSs, just in case future tests need it
> Small bug fixes

- linux/lib/mprisService.js
This will fix issue #78 
The fix will work with an updated version of Headset Core. If an older version is used (the current version), it doesn't cause any problems, so it's safe to be merged.
> Changes volume slider when updated from MPRIS

- darwin/index.js
- linux/index.js
- windows/index.js
This is a small fix for a very annoying bug (in my opinion). 
I hated the fact that I couldn't start typing to search as soon as Headset finished opening. It's one of those tiny things that almost nobody notices, but was driving me crazy :nerd_face: 
I totally understand if this is so insignificant that doesn't deserve to be merged, this PR is mainly for my own sake :smile:
> Focus main window after player-window finished loading

- bin/choco_version_bump.sh
- windows/bin/build_choco.ps1
The file `chocolateyInstall.ps1` has a `version` variable inside that was being changed only by AppVeyor when releasing. The resulting package would have worked without problems, but our code will always show `1.7.0` as the version. This PR changes that version number when running `npm version ...` rather than inside of the AppVeyor `build_choco.ps1` script. Now all files that have a version number will show the appropriate version.
> Commit version into chocoInstall script when releasing a new version

- .travis.yml
- appveyor.yml
- darwin/bin/build_pack.sh
- darwin/package-lock.json
- darwin/package.json
- linux/bin/build_package.sh
- linux/package-lock.json
- linux/package.json
- package-lock.json
- package.json
- windows/package-lock.json
- windows/package.json
This PR updates all modules to the latest versions, most importantly `electron-packager`. And creates reliable `package-lock.json` for each OS and the root directory.
Travis and AppVeyor will use [`npm ci`](http://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable) to install all dependencies, with the exception of OSX where one of the dependencies is not working properly with `npm ci` and throwing errors.
> Use npm ci

- .travis.yml
- README.md
- appveyor.yml
- darwin/bin/build_dist.sh
- darwin/package-lock.json
- darwin/package.json
- linux/bin/config_deb.json
- linux/package-lock.json
- linux/package.json
- windows/index.js
- windows/package-lock.json
- windows/package.json
This PR not only updates electron for all OSs, but also fixes a bug that was preventing us from seeing any error when packaging for macOS on Travis.
Also, we updated to `npm@6.1.0` and the default node version is `8` now, which is a requirement for some macOS modules.
> Electron 2.0

- windows/index.js
- windows/lib/headsetTray.js
- windows/package-lock.json
- windows/package.json
Logging to the terminal doesn't seem to work with any version of electron for windows.
This will allow us to log into a file to check for errors.
> Log windows debug messages to file

- darwin/package-lock.json
- darwin/package.json
- linux/package-lock.json
- linux/package.json
- package-lock.json
- package.json
- windows/package-lock.json
- windows/package.json
This PR will solve the failing Linux build on Travis due to malware found in one of the dependencies of `dbus-native`
I contacted the developer of `dbus-native` and a new version was released.
> Update dbus-native (and other minor modules)

- package-lock.json
- package.json
- src/lib/mprisCover.js
- src/lib/mprisService.js
Originally, we were passing to MPRIS the thumbnail URL. MPRIS would download the image but it's a rectangle, so MPRIS will squash it and the image would look distorted.
Now, we download the image ourselves (the smallest available ~4kB), crop it, save it to disk, and give MPRIS the URI to the file.
We save the image on the default config directory for electron apps with a default name and always overwrite it, so there's never a problem with too many files, or running out of disk space.
So, we move the downloading of the cover image from MPRIS to Headset, so there's no additional network usage.
We fall back to the old behavior if the downloading, cropping, or saving to disk fails.
> fix mpris album covers

- package-lock.json
- package.json
contributor-faces is causing alerts for vulnerabilities on Github. It's not likely that the package will be updated. I even tried to fix those issues myself but more issues came out afterward.
Given that we only use it to update the README, it'll be better to install it globally rather than a dependency on this project.
> fix: remove contributor-faces and use globally installed version

- .github/workflows/ci.yml
Ubuntu 20.04 (which is now used by GitHub Actions) has removed the package createrepo, which is needed to build the rpm repository
> ci: use ubuntu-18.04

- .github/workflows/ci.yml
- bin/installer/redhat_sign.sh
- bin/linux_repo.sh
- package.json
RedHat installer was only being signed for the repository, it should
always be signed for distribution.
> ci: sign RedHat installer for GitHub release

- src/lib/discord.js
If there were any issue with Discord integration in the past, this
should fix them
> fix: use correct WebContents when executing javascript code

- src/lib/autoUpdater.js
- src/lib/headsetLogger.js
Errors are still logged in the default file but users won't be disturbed by the dialog
fixes #395
> fix: don't show error dialogs for updating errors

- .husky/pre-push
The test was using whatever the build directory contained, which is not necessarily the latest code.
We now package the latest code before testing.
> build: always package the latest code for husky pre-push hook

- .github/workflows/ci.yml
This also removes the need to update npm because node@16 includes npm >= 7
> ci: use nodejs 16

- .github/workflows/ci.yml
- package-lock.json
- package.json
- src/index.js
- test/app.test.js
- test/linux/installers.test.js
- test/logs.js
We can now display logs inside of `ava` testing and we're catching errors as soon as possible, even before importing any of our own library modules
> Better handle of logging, specially in tests

- .github/workflows/ci.yml
- .gitignore
This is useful for testing builds without having to create a PR.
Also great for sharing builds with users which has the advantage of having the installers signed.
> ci: create artifacts only for the 'artifact' branch

- src/lib/discord.js
For some reason, Date is returning null which causes RPC to error.
Fix #503
> fix: always have a value for Discord start/end timestamps

- src/lib/discord.js
It seems there are weird cases where Discord can crash, we are just covering our bases.
> fix: always have a title for Discord

- .github/workflows/ci.yml
- bin/linux_repo.sh
Ubuntu 20.04 doesn't have any version of createrepo, so we never upgraded.
New Ubuntu contains a replacement createrepo-c
> ci: switch to ubuntu-22.04
